### ISSUE TITLE
Need to include xAct context when defining new tensor

### ISSUE THREAD

**Issue by samdupton** [BlackHolePerturbationToolkit/PerturbationEquations#10]
When defining a new tensor, one cannot simply use the names that are defined in the package source, e.g. `R2`, `S2` and `M4`. Instead, one must use the names with the xAct context prepended to them, e.g. ``xAct`PerturbationEquations`Private`M4``.

For example, `DefTensor[test[], M4]` gives the output `DefTensor: Unknown dependency M4.` but ``DefTensor[test[], xAct`PerturbationEquations`Private`M4]`` works to define the tensor.

**Comment by barrywardell** [comment]
We should fix this by making sure that all symbols defined by xAct are in the public package context.

**Comment by adamrpound** [comment]
I've now moved the entire Definitions section into the public context. But I'll leave this issue open for someone else to check.

**Comment by adamrpound** [comment]
I've been using the package successfully with added tensors, so I'm closing this issue.
