### ISSUE TITLE
Automatically set CInt to 0 when unphysical mode numbers are chosen

### ISSUE THREAD

**Issue by samdupton** [BlackHolePerturbationToolkit/PerturbationEquations#11]
Is it worth incorporating the rules for when the 3j-symbols vanish to the level of the CInt command? It should substantially shorten any output of `SchwarzschildQuadraticOperator` when working with specific mode numbers.

**Comment by barrywardell** [comment]
Yes, at the very least I think we could use Quiet[..., ClebschGordan::phy] to remove the warning messages and then rely on the fact that ThreeJSymbol returns 0 in those cases.
