### ISSUE TITLE
SchwarzschildLinearOperator trTensor basis components mixing parity

### ISSUE THREAD

**Issue by thompsonphys** [BlackHolePerturbationToolkit/PerturbationEquations#21]
Evaluating `SchwarzschildLinearOperator["dG", "Generic", "trTensor", "trTensor"]` for the spin-1 components (e.g. "t+", "r-" etc.) produces output containing both even- and odd-parity pieces. An example output is given below.

![Screenshot 2023-09-14 at 15 09 06](https://github.com/BlackHolePerturbationToolkit/PerturbationEquations/assets/43813555/42c7893b-85d3-43df-a47b-c0eef6124d52)

As we can see, these opposite-parity pieces always show up with an explicit factor of `i` in front. I'm wondering if one of the vector harmonic projection rules might be broken.

**Comment by thompsonphys** [comment]
Some minor updates/comments about some strange versioning confusion that I'm encountering (as we discussed a bit on a call). Perhaps @barrywardell knows some of the nuances here.

I've cloned `PerturbationEquations` and symlinked the repository into my `$UserBaseDirectory/Applications` folder (equivalently inside the xAct folder). When calling ``<<xAct`PerturbationEquations` ``, I recover version 0.0.1 {2023, 6, 30} which does not include some of the recent changes that @adamrpound has implemented.

On the other hand, if I explicitly use `SetDirectory` to the kernel path of `PerturbationEquations` and load `<<PerturbationEquations.wl`, then I load version 0.1.0 {2023, 6, 30} which *does* include the changes recently committed. Is there any advice on how to potentially avoid this confusion in the future while loading through `xAct`, or is loading `PerturbationEquations.wl` directly the recommended approach when working with unreleased development code in Mathematica?

Just as a note, the parity issue above still remains in the more recent version of the code.

**Comment by barrywardell** [comment]
I recommend only every installing using the [Paclet system](http://bhptoolkit.org/mathematica-install). If you need to try out a development version from git, then you should follow the [developer instructions](http://bhptoolkit.org/mathematica-install-dev) to temporarily use a version checked out from git. You should avoid putting things in $UserBaseDirectory/Applications or similar as they could cause confusion.

**Comment by adamrpound** [comment]
@barrywardell Can you reproduce Jonathan's issue with the mixed parity? I don't get the problematic terms when I run the same command as Jonathan.

**Comment by barrywardell** [comment]
With version 0.1.0 I get
<img width="698" alt="Screenshot 2023-09-16 at 13 57 12" src="https://github.com/BlackHolePerturbationToolkit/PerturbationEquations/assets/354095/f7998046-ddae-4a7f-9603-be7c82c7d3d9">
whereas with the current main branch (4705f25) I get
<img width="592" alt="Screenshot 2023-09-16 at 13 58 00" src="https://github.com/BlackHolePerturbationToolkit/PerturbationEquations/assets/354095/2ca06065-c3d4-4653-a1fd-8ac1396c82c8">

**Comment by adamrpound** [comment]
I realized that the output is actually correct. The terms with the wrong parity are multiplied by zero. It's just not obvious until you use mutolrule. I've updated the package to set these terms to zero.
