### ISSUE TITLE
Singular results for ell=0,1 input modes

### ISSUE THREAD

**Issue by adamrpound** [BlackHolePerturbationToolkit/PerturbationEquations#3]
In the BLS basis, d2G becomes singular for ell=0,1 first-order input modes. For example, SchwarzschildQuadraticOperator["d2G", "Generic", "BLS", "BLS"][[1]] returns 1/0^2 if l1=0 and l2=1. The singularity occurs due to powers of 1/mu[LI[l],-LI[s]].

**Comment by barrywardell** [comment]
This is now fixed.
