### ISSUE TITLE
Need to convert the xAct quantities into mathematica variables

### ISSUE THREAD

**Issue by DrAndrewSpiers** [BlackHolePerturbationToolkit/PerturbationEquations#4]
Things that look fine in output have horrible inputs which are hard to work with

SchwarzschildPerturbations`h[{3, -SchwarzschildPerturbations`NP}, {
 4, -SchwarzschildPerturbations`NP}, 
xAct`xTensor`LI[0], 
xAct`xTensor`LI[SchwarzschildPerturbations`l1], 
xAct`xTensor`LI[SchwarzschildPerturbations`m1]]

Also, use Format[expr,form] for subsripts

**Comment by barrywardell** [comment]
This has been fixed.
